# Worksheet 04

Name:  Chris Chan

UID: U31827126

Partner: Haya Al-Majali

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d is the dimensionality of the space

p is a parameter that specifies the type of distance metric

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance measures the shortest path between two points in any direction.

The Manhattan distance measures the distance between points by only travelling in the direction of the basis vectors.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

When p gets very large, the distance between A and B will approach 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

When p < 1, the minkowski distance is not a distance function.

This is because the triangle inequality does not hold if you take points A(0, 0), B(1, 0), and C(0, 1)

D(B, A) = D(A, C) = 1

D(B, C) = 2 ^ (1/p)

So D(B, C) > D(B, A) + D(A, C)

e) when would you use cosine similarity over the euclidan distance?

Cosine similarity is more useful over Euclidean distance when direction matters over distance. This is also useful when distances cannot be normalized. An example when this is useful is in understanding language, where concepts can be represented in some high dimensional direction. 

f) what does the jaccard distance account for that the manhattan distance doesn't?

The jaccard index accounts for the size of the intersection between two samples weighted inversely as the size of the sample. The manhattan distance weights each part of the sample with the same weight.

#### Part 2

Consider the following two sentences:

In [8]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [9]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [10]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'is', 'Alice', 'my', 'name', 'Bob']
[1, 1, 1, 1, 1, 0]


Let's add a new sentence to our corpus:

In [11]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [12]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hello', 'Claude', 'is', 'Alice', 'hi', 'my', 'name', 'Bob']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [13]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]

print(f"v1: {v1}")
print(f"v2: {v2}")
print(f"v3: {v3}")

v1: [1, 0, 1, 1, 0, 1, 1, 0]
v2: [1, 0, 1, 0, 0, 1, 1, 1]
v3: [0, 1, 1, 0, 1, 1, 1, 0]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [14]:
import numpy as np

def manhattan_distance(v1, v2):

    if len(v1) != len(v2):
        raise RuntimeError("x and y should be the same dimension")

    v1 = np.array(v1)
    v2 = np.array(v2)
    return np.sum(np.abs(v1 - v2))

print(f"v1 - v2: {manhattan_distance(v1, v2)}")
print(f"v1 - v3: {manhattan_distance(v1, v3)}")
print(f"v2 - v3: {manhattan_distance(v2, v3)}")


v1 - v2: 2
v1 - v3: 4
v2 - v3: 4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [16]:
s4 = "hi Alice"
s5 = "hello Claude"
s6 = "Bob my name is Claude"
s7 = "hi Claude my name is Alice"
s8 = "hello Bob"

corpus = [s1, s2, s3, s4, s5, s6, s7, s8]
all_words = list(set([item for x in corpus for item in x.split()]))

new_vecs = [[1 if x in s else 0 for x in all_words] for s in corpus]
matrix = np.array(new_vecs)
print(all_words)
print(matrix)


['hello', 'Claude', 'is', 'Alice', 'hi', 'my', 'name', 'Bob']
[[1 0 1 1 0 1 1 0]
 [1 0 1 0 0 1 1 1]
 [0 1 1 0 1 1 1 0]
 [0 0 0 1 1 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 1 1 0 0 1 1 1]
 [0 1 1 1 1 1 1 0]
 [1 0 0 0 0 0 0 1]]


e) How many rows and columns does this matrix have?

In [17]:
R, C = np.shape(matrix)
print(f"The matrix has {R} rows and {C} columns")

The matrix has 8 rows and 8 columns


f) When using the Manhattan distance, which two sentences are the most similar?

In [42]:
distances = np.ones((R, R)) * np.inf
for row in range(R):
    for col in range(row + 1, C):
        distances[row, col] = manhattan_distance(matrix[row], matrix[col])

min_distance = np.min(distances)
sentence1, sentance2 = np.nonzero(distances == min_distance)
print(f"The words with the shortest distance is s{sentence1[0]} and s{sentance2[0]}")

The words with the shortest distance is s2 and s6


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [90]:
def compute_distances(graphs):
    graphs = np.array(graphs)
    graphs = np.triu(graphs)
    
    B, V, _ = np.shape(graphs)
    graph_matrix = np.expand_dims(graphs, axis=0)
    graph_matrix = np.repeat(graph_matrix, B, axis=0)

    graph_matrix_t = np.transpose(graph_matrix, axes=(1, 0, 2, 3))
    diff_edges = np.not_equal(graph_matrix, graph_matrix_t)

    distances = np.sum(np.sum(diff_edges, axis=3), axis=2)
    return distances

In [96]:
import pytest
import ipytest

def test_compute_distance():
    # arrange
    graphs = [
        np.array([
            [0, 1, 0],
            [1, 0, 0],
            [0, 1, 0]
        ]),
        np.array([
            [0, 1, 1],
            [1, 0, 0],
            [1, 1, 0]
        ]),
        np.array([
            [1, 0, 0],
            [0, 0, 0],
            [0, 0, 0]
        ]),
        np.array([
            [1, 1, 1],
            [1, 0, 0],
            [1, 0, 0]
        ])
    ]
    expected = np.array([
        [0, 1, 2, 2],
        [1, 0, 3, 1],
        [2, 3, 0, 2],
        [2, 1, 2, 0],
    ])

    # Act
    actual = compute_distances(graphs)

    # Assert
    assert np.all(actual == expected)

ipytest.run()



======================================= test session starts =======================================
platform win32 -- Python 3.11.7, pytest-8.0.0, pluggy-1.4.0
rootdir: c:\Users\chris\bu\spring2024\Data-Science-Fundamentals\lecture_04
plugins: anyio-3.6.2
collected 1 item

t_0d467f043d8249b08cd5472dfd354d96.py .                                                      [100%]

======================================== 1 passed in 0.07s ========================================


<ExitCode.OK: 0>